version: '3.8'

services:
  app:
    build: .
    container_name: regex-generator
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped